config/routes.rb
Rails.application.routes.draw do
  # facebook chatbot routes
  get 'callback/index'
  post 'callback/index' => 'callback#recieved_data'
  get 'callback/recieved_data'
  # dialogflow chatbot routes
  post 'messages/index' => 'messages#send_message'
  get 'messages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  #Facebook chatbot
  protect_from_forgery with: :null_session

  def index
    if params["hub.verify_token"] == "your_token"
      render text: params["hub.challenge"]
    end
  end

  def recieved_data
    therequest = request.body.read
    data = JSON.parse(therequest)
    entries = data["entry"]
    entries.each do |entry|
      entry["messaging"].each do |messaging|
        sender = messaging["sender"]["id"]
        text = messaging["message"]["text"]
        myjson = {"recipient": {"id": "#{sender}"},"message": {"text": "#{text}"}}
        puts HTTP.post(url, json: myjson)
      end
    end
    render "recieved_data"
  end

  def url
    "https://graph.facebook.com/v2.6/me/messages?access_token=your_token"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  #Dialogflow chatbot
  def index
  end

  def send_message
    @client = ApiAiRuby::Client.new(
        :client_access_token => '<your_code>' #Here put your client access token from your API.ai account
    )
    @text = params[:message]
    @response = @client.text_request("#{@text}")
    puts @message = @response[:result][:fulfillment][:speech]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callback_helper.rb
module CallbackHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/callback/index.html.erb
<h1>Callback#index</h1>
<p>Find me in app/views/callback/index.html.erb</p>
<%= @params %>

app/views/callback/recieved_data.html.erb
<h1>Callback#recieved_data</h1>
<p>Find me in app/views/callback/recieved_data.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<div class="container">
  <h1>Bienvenido al ChatBot</h1>

  <!-- CHATBOX -->
    <div class="chat-main">
      <div class="offset-md-8">
        <div class="col-md-12 chat-header rounded-top bg-primary text-white">
            <div class="row">
                <div class="col-8 username pl-2">
                    <i class="fa fa-circle text-success" aria-hidden="true"></i>
                    <h6 class="m-0">Cirilo</h6>
                </div>
                <div class="col-4 options text-right pr-2">
                    <i class="fa fa-times hide-chat-box" aria-hidden="true"></i>
                  </div>
            </div>
        </div>
        <div class="chat-content">
            <div class="col-md-12 chats border">
                <ul class="p-0">
                  <div id="chat">
                  </div>
                </ul>
            </div>
            <div class="col-md-12 message-box border pl-2 pr-2 border-top-0">
              <%= form_with url: messages_index_path do |f| %>
                <div class="row">
                  <div class="col-10">
                    <%= f.text_field :message, class: "pl-0 pr-0 w-100 form-control-sm", id: "text", placeholder: "Type a message..."%>
                  </div>
                  <div class="col-2 tools text-center">
                    <%= button_tag(type: 'submit', class: "hide-btn") do %>
                      <i class="fa fa-telegram" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
    </div>
  </div>
  <!-- END OF CHATBOX -->
</div>

app/views/messages/send_message.js.erb
$("#text").val('');
$('#chat').append('<li class="pl-2 pr-2 bg-primary rounded text-white send-msg mb-1"> '+ '<%= @text %>' +'</li>' );
$("#chat").append('<li class="p-1 rounded mb-1"><div class="receive-msg"><div class="receive-msg-desc mt-1 ml-1 pl-2 pr-2"><p class="pl-2 pr-2 rounded"><%= @message %></p></div></div></li>');